[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate && python setup_database.py",
  ". /opt/venv/bin/activate && python data_processor.py"
]

[start]
cmd = ". /opt/venv/bin/activate && streamlit run dashboard.py --server.port=$PORT --server.address=0.0.0.0" 